title: "TOUKEBRI Wael"
email: ""
description: "Portfolio of TOUKEBRI Wael â€“ Junior AWS Solutions Architect passionate about cloud computing, scalable infrastructure, and secure architecture. Explore my work with EC2, S3, CloudFront, IAM, Auto Scaling, and more."

# Add these lines to exclude CSS files from processing
exclude:
  - "*.css"
  - "*.scss"
  - "*.sass"
  - "assets/*.css"
  - "_layouts/*.css"

social:
  - title: linkedin
    url: ""
  - title: github
    url: ""
  - title: email
    url: "wael4toukebri@gmail.com"
