title: TOUKEBRI Wael
  email: 
description: "Portfolio of TOUKEBRI Wael â€“ Junior AWS Solutions Architect passionate about cloud computing, scalable infrastructure, and secure architecture. Explore my work with EC2, S3, CloudFront, IAM, Auto Scaling, and more."

social:
  - title: linkedin
    url: 
  - title: github
    url: 
  - title: email
    url: wael4toukebri@gmail.com
